### ISSUE TITLE
[Request] Porting some patches for getting great performance

### ISSUE THREAD

**Issue by NovaPixell** [foss-mc/Patina#1]
I recently installed Patina on my vanilla server and I can say that with 110 users I have excellent results.
45 ms and 19 TPS.
With 40k Tile Entities and 4k entities.

I don't want all the Yatopia patches to be brought, but there are many interesting patches that greatly optimize servers with high numbers of players.

These patches are:

1. https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.5/patches/server/0016-Heavily-optimize-furnance-fuel-and-recipe-lookups.patch
2. https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.5/patches/server/0039-Heavily-optimize-recipe-lookups-in-CraftingManager.patch
3. https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.5/patches/server/0065-lithium-skip-ticking-block-entities-that-are-doing-n.patch

The third patch is very useful for servers that have high amounts of TE.

Please consider importing these patches, as a performance boost can be achieved

**Comment by etil2jz** [comment]
Up 😃
