### ISSUE TITLE
Invisible Player after death when player come back to his old locations of death

### ISSUE THREAD

**Issue by Symeloxk** [foss-mc/Patina#12]
Please solve this bug.. 

I'm in Patina 1.17.1

**Comment by INotSleep** [comment]
More details.

**Comment by toinouH** [comment]
@Symeloxk 
Hello,
Would you provide more details like the version (point me the commit :D); plugins; and maybe timings so we have your settings.
Have a nice day.

**Comment by toinouH** [comment]
Got this once on 1.18.2 last week; not sure that's Patina.
