### ISSUE TITLE
Please fix the lectern crash server issue before version 1.18.2

### ISSUE THREAD

**Issue by killerprojecte** [foss-mc/Patina#17]
After Minecraft 1.14 it has a bug from the lectern which crashes the server. Paper fix it in 1.18.2 , But older version is not support.

I think Patina need fix it
Of course, If Your need me to help. I can fix it.

**Comment by toinouH** [comment]
@killerprojecte Assuming this is https://github.com/pufferfish-gg/Pufferfish/commit/42ef3dcc14ba1013dbdde39e9641c698790c346d
For 1.16.5 it might be "unfixable", toothpick does not work anymore and I don't think it's worth the effort.

Any pr are welcome if you want to fix the 1.17.1 (and 1.17 and pre 1.18.2 version if you think that's necessary)

**Comment by killerprojecte** [comment]
@toinouH 
lol i think u need know some version NMS Mapping are diffrent.
I already fix it for myself released 1.16.5 purpur fork

public ItemStack shiftClick(EntityHuman entityhuman, int i)
