### ISSUE TITLE
All mobs (including passive) is vanishing

### ISSUE THREAD

**Issue by txkxhxshi** [foss-mc/Patina#18]
I created my server on Patina 1.18.2. The problem is that all mobs, including villagers and peaceful mobs, despawn when reconnecting to the server, if you go too far and when the server is restarted.
Also there are no villagers in the villages. My friend and I removed all the plugins one by one, but the problem turned out to be in the core. Here are my plugins:
Better Sleeping 4
AuthMe 5.6.0 beta2
Core Protect 21.2
GSit 1.0.10
LuckPerms 5.4.25
OpenInv
Plasmo voice 1.0.10
ProtocolLib
SkinsRestorer
TabList bukkit 5.6.2
WorldBorder

And datapack Player head drops

**Comment by Plasticable** [comment]
Same problem

**Comment by Vahulan** [comment]
same problem

**Comment by curkan** [comment]
same problem

**Comment by foss-mc** [comment]
Related issue for 1.19: https://github.com/PatinaMC/Patina/issues/23

**Comment by ghost** [comment]
@txkxhxshi What version of Patina 1.18.2 did you use?

**Comment by YouMasiksCrush** [comment]
How fix this problem, i have the same problem, why this core is the best of each other but this little problem still not fixed????!?!?
