### ISSUE TITLE
[New Branch Request] Purpur Branch

### ISSUE THREAD

**Issue by NovaPixell** [foss-mc/Patina#2]
Patina is a great software, very useful for survival servers with many entities and tile entities.
It would be useful a Patina branch with the complete Purpur upstream would be created and updated over time. As many servers use different features of Purpur

**Comment by Toffikk** [comment]
The best thing would be to make Airplane-Purpur upstream instead of Paper without squashing other forks

**Comment by NovaPixell** [comment]
Why not? May be nice!
The important thing is that all the Patina optimization patches are in

**Comment by toinouH** [comment]
At the moment we added some "features patches" from Purpur, we know that's not ideal but it would be unmaintainable.
I think we should keep that issue opened until we find a good solution for everyone: maintainers; contributors and server owners.

**Comment by KaspianDev** [comment]
i agree to this

**Comment by SnakesServ** [comment]
agree
