### ISSUE TITLE
Shulkers don't spawn

### ISSUE THREAD

**Issue by aliaksei-hryharovich** [foss-mc/Patina#22]
latest(at the time of issue creation) patina 1.19

**Comment by aliaksei-hryharovich** [comment]
Paper is ok

**Comment by curkan** [comment]
Villagerss won't spawn either. What could be the reason?

**Comment by ghost** [comment]
@curkan The latest patina build fixes this problem

**Comment by ghost** [comment]
@Alexei-Grigarovich Give more details

**Comment by aliaksei-hryharovich** [comment]
If you come to any end city, then there will be no shulkers

**Comment by ghost** [comment]
Try the latest version of Patina
