### ISSUE TITLE
Passive mobs disappear

### ISSUE THREAD

**Issue by AsrielStory** [foss-mc/Patina#23]
All passive mobs disappear including residents, but cats remain
(patina-paperclip-1.19-R0.1-SNAPSHOT-reobf)
Plugins:
elyby-skinsystem-0.2.0-beta
GSit-1.1.0
plasmovoice-server-1.0.10

**Comment by foss-mc** [comment]
A person reported that mobs reappeared after switching to Purpur

**Comment by foss-mc** [comment]
Related issue for 1.18: https://github.com/PatinaMC/Patina/issues/23

**Comment by foss-mc** [comment]
fixed in https://github.com/PatinaMC/Patina/commit/cb14525492ba6ad2c996e6cbf91f1698219da0ad
