### ISSUE TITLE
bees

### ISSUE THREAD

**Issue by dedokok** [foss-mc/Patina#32]
why bees on my patina server die when they leave the beehive? 1.19
https://youtu.be/HUrrpAkVAyw

**Comment by foss-mc** [comment]
Suffocation logic seems broken for some reason.

investigating it..

**Comment by CuteLittleSky** [comment]
> Suffocation logic seems broken for some reason.
> 
> investigating it..

I encountered that after releasing the bees from the hive, but the bees inside the hive still did not disappear
https://youtu.be/y8OJdcI9bZs
