### ISSUE TITLE
Pufferfish Performance Patches

### ISSUE THREAD

**Issue by NovaPixell** [foss-mc/Patina#7]
I discovered a new fork named [Pufferfish](https://github.com/pufferfish-gg/Pufferfish), there are some interesting patches. What do you think?

**Comment by toinouH** [comment]
May be useful for 1.18 I guess.
It's up to @foss-mc to decide :)

**Comment by toinouH** [comment]
This is done in the 1.18 branch. I'm closing this and thank you for the suggestion :)
